server.port: 7000
server.error.include-message: always

app:
  game-service:
    host: localhost
    port: 7001
  review-service:
    host: localhost
    port: 7002
  dlc-service:
    host: localhost
    port: 7003
  event-service:
    host: localhost
    port: 7004

logging:
  level:
    root: INFO
    vladimir: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
server.port: 8081

app:
  game-service:
    host: game
    port: 8081
  dlc-service:
    host: dlc
    port: 8081
  review-service:
    host: review
    port: 8081
  event-service:
    host: event
    port: 8081
