server.port: 8081

spring.application.name: gateway

app.config-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

spring.cloud.gateway.routes:

 - id: config-server
   uri: http://${app.config-server}:8888
   predicates:
   - Path=/config/**
   filters:
   - RewritePath=/config/(?<segment>.*), /$\{segment}

ribbon.ServerListRefreshInterval: 5000

ribbon.NFLoadBalancerPingInterval: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

---
spring.profiles: docker

app.config-server: config-server