server.port: 7001
server.error.include-message: always

logging:
  level:
    root: INFO
    vladimir: DEBUG

spring:
  mongodb:
    embedded:
      version: 3.5.5
      
  data:
    mongodb:
      auto-index-creation: true
---
spring:
  config:
    activate:
      on-profile: docker

server.port: 8081
