server.port: 7002
server.error.include-message: always

logging:
  level:
    root: INFO
    vladimir: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

spring:
  mongodb:
    embedded:
      version: 3.5.5
      
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
      port: 27017
      database: review-db  
---
spring:
  config:
    activate:
      on-profile: docker

server.port: 8081
spring.data.mongodb.host: mongodb