eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
  server:
    response-cache-update-interval-ms: '5000'
    wait-time-in-ms-when-sync-empty: 0
server:
  port: 8761
